version: '3'
services:
  admin:
    build: ./packages/admin
    env_file: ./.env
    volumes:
      - ./packages/admin:/app
    ports:
      - "${ADMIN_PORT}:5173"
    networks:
      app:
        ipv4_address: 10.21.0.2

  app:
    build: ./packages/app
    env_file: ./.env
    volumes:
      - ./packages/app:/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      app:
        ipv4_address: 10.21.0.3
  api:
    build: ./packages/api
    env_file: ./.env
    volumes:
      - ./packages/api:/app
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      app:
        ipv4_address: 10.21.0.4
  core:
    build: ./packages/core
    env_file: ./.env
    volumes:
      - ./packages/core:/app
    ports:
      - "${CORE_PORT}:3000"
    networks:
      app:
        ipv4_address: 10.21.0.5

networks:
  app:
    driver: bridge
    ipam:
      config:
        - subnet: 10.21.0.0/16
          gateway: 10.21.0.1
